//DIFFERENT ACTION TYPES CALLED BY INDEX.JS IN ACTIONS

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_INFO = 'USER_INFO';
export const RECEIVE_DATA = "RECEIVE_DATA";
